project:
  type: website
  output-dir: docs
  
website:
  title: "yanlinfeng123b.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmq

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

